### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by ilil96** [pdclab/peregrine#16]
Hi, when I make, I get a lot of "undefined reference to 'tbb::~~~'" errors like the following.
`core/DataConverter.o:(.data.rel.ro+0x10): undefined reference to typeinfo for tbb::task`

I'm working on Ubuntu 18.04 and faithfully followed the instructions in README.
Is there anything that I can try?

Thank you
